[package]
name = "chip8-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
emulator-core.workspace = true
sdl2 = "0.38.0"

[workspace]
resolver = "2"
members = ["emulator-core"]

[workspace.dependencies]
emulator-core = { path = "emulator-core" }
